### ISSUE TITLE
Something wrong in calculating metrics

### ISSUE THREAD

**Issue by JuewenPeng** [Glass-Imaging/NTIRE23BokehTransformation#3]
In function 'calculate_psnr(img0, img1)', the type of the input is 'uint8'. It may cause an error when subtracting 'img0' and 'img1'. For example, 0 - 170 = 86.

**Comment by mako443** [comment]
Hi @JuewenPeng ,
Thanks for messaging us and great catch! 
I've made a small fix by converting both images to float32 first.

Best of luck with the challenge, please let us know if you have any more questions.
